
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: ${SERVER_PROMETHEUS_NAME}
    restart: always
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PORT_PROMETHEUS}:9090"
    networks:
      - loki-net
      
  loki:
    image: grafana/loki:2.9.5
    container_name: ${SERVER_LOKI_NAME}
    restart: always
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/config:/etc/loki:ro
      - ./loki/data:/loki
    ports:
      - "${PORT_LOKI}:3100"
    logging: *default-logging
    networks:
      - loki-net

  grafana:
    image: grafana/grafana:10.4.2
    container_name: ${SERVER_GRAFANA_NAME}
    restart: always
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${SERVER_GF_SECURITY_ADMIN_PASSWORD}
      - SERVER_LOKI_NAME=${SERVER_LOKI_NAME}
      - PORT_LOKI=${PORT_LOKI}
    ports:
      - "${PORT_GRAFANA}:3000"
    logging: *default-logging
    networks:
      - loki-net

networks:
  loki-net:
    driver: bridge
    name: loki-net